services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./instance:/app/instance 
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: sqlite:////app/instance/events.db
